site_name: OWASP Operational Technology (OT) Top 10
site_url: https://ot.owasp.org
repo_url: https://github.com/OWASP/www-project-operational-technology-top-10
theme:
  name: material
  features:
    #- navigation.sections
    #- navigation.expand
    - navigation.tracking
    - navigation.path
    - navigation.top
    #- navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - sane_lists

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/OWASP/www-project-operational-technology-top-10
  analytics:
    provider: google
    property: G-MGPB7M04WE

copyright: |
  <div style="float: left; padding-right: 1em;">
    <a href="https://www.owasp.org"><img src="https://github.com/OWASP/owasp-mastg/blob/master/Document/Images/OWASP_logo_white.png?raw=true" width="100px" /></a>
  </div>
  <span style="font-size: smaller">
    &#169; OWASP Foundation 2024. This work is licensed under 
    <a href="https://creativecommons.org/licenses/by/4.0">CC-BY-4.0</a>. For any reuse or distribution, you must make clear to others the license terms of this work.
  </span><br><span style="font-size: smaller">OWASP &#174; is a registered trademark of the OWASP Foundation, Inc.</span> <span>This website uses cookies to analyze our traffic and only share that information with our analytics partners. <a href="https://github.com/OWASP/owasp-mastg/blob/master/about_cookies.md">Learn more</a>.</span>

nav:
  - 'Start Here': index.md
  - 'Introduction':
    - 'About OWASP': introduction/about-owasp.md
    - 'How to contribute?': introduction/contributing.md
    - 'Contributors': introduction/contributors.md
    - 'Related OWASP Projects': introduction/related-owasp-projects.md
  - 'Operation Technology (OT)':
    - background-ot/index.md
    - 'Saftey vs. Security': background-ot/safety-vs-security.md
    - "OT for IT Sec People": background-ot/ot_for_itsec_people.md
    - "IT Sec for OT People": background-ot/itsec_for_ot_people.md
    - 'Standards and Regulations': background-ot/related-standards.md
  - 'The Top 10':
      - the-top-10/index.md
      - '1. Unknown Assets and Undocumented Services': the-top-10/unknown-assets-and-admin-access.md
      - '2. Devices with known Vulnerabilities': the-top-10/accessible-devices-with-known-vulnerabilities.md
      - '3. Inadequate Supply Chain Management': the-top-10/inadequate_supply_chain_management.md
      - '4. Insufficient Access Control': the-top-10/insufficient-access-control.md
      - '5. Missing Incident Detection/Reaction Capabilities': the-top-10/missing-incident-detection-reaction-capabilities.md
      - '6. Broken Zones and Conduits Design': the-top-10/broken-zone-and-conduits-design.md
      - '7. Missing Awareness': the-top-10/missing-awareness.md
      - '8. Insufficient Security Capabilities': the-top-10/components-with-insufficient-security-capabilities.md
      - '9. Loss of Availability': the-top-10/loss-of-availability.md
      - '10. Missing Hardening': the-top-10/missing-hardening.md
  - 'Appendix':
    - "What's next?": appendix/whats-next.md
    - 'Standards Mapping Table': appendix/mappingTable.md
    - 'Glossary': appendix/glossary.md
